package application;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;
import javafx.scene.image.ImageView;
import javafx.stage.Stage;
import javafx.event.ActionEvent;

public class MainSceneController {
	@FXML
	private TextField tfTitle;
	
	@FXML ImageView view1;
	@FXML ImageView view2;
	// Event Listener on Button.onAction
	@FXML
	public void btnOkClicked(ActionEvent event) {
		// TODO Autogenerated
		Stage mainWindow = (Stage) tfTitle.getScene().getWindow();
		String title = tfTitle.getText();
		mainWindow.setTitle(title);
	}
}


